<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:math="http://www.w3.org/2005/xpath-functions/math"
  xmlns="http://hcmc.uvic.ca/ns/staticSearch"
  exclude-result-prefixes="#all"
  version="3.0">
  
  <!--
    Read in the “semantic” XML version of the IANA language subtag registry
    (itself generated by running my IANA_lang_registry_in_XML.xslt over the
    JSON version of the IANA registry generated by running `make update` in
    the https://github.com/mattcg/language-subtag-registry/ directory; and
    write out a UVEPSS <contexts> element with one <context> for each lang-
    uage.
    Written 2024-03-23 by Syd Bauman. Copyleft by the author.
  -->
  
  <xsl:output method="xml" indent="yes"/>
  <xsl:mode on-no-match="deep-skip"/>
  
  <xsl:template match="/">
    <contexts>
      <xsl:apply-templates select="/*/language"/>
    </contexts>
  </xsl:template>
  
  <xsl:template match="language">
    <xsl:variable name="description" as="xs:string" select='translate( normalize-space(.), "&apos;","’")'/>
    <context label="Language: {$description}" match="text()[ lang(&apos;{@subtag}&apos;) ]"/>
  </xsl:template>
  
</xsl:stylesheet>