name: validate relaxng

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Validate articles
      uses: rlskoeser/xmllint-action@support-other-schemas
      with:
        xml-file: articles/[0-9]*/*.xml
        xml-schema-file: common/schema/DHQauthor-TEI.rng
        xml-schema-type: relaxng
