name: validate relaxng

on: [push]

jobs:
  validate-relaxng:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Count articles
      run: echo '::set-output name=TOTAL::`ls articles/[0-9]*/*.xml | wc -l`'
      id: article-count
    - name: Output article count
      run: echo "Validating ${{ steps.article-count.outputs.TOTAL }} articles" >> GITHUB_STEP_SUMMARY
    - name: Enable xmllint matcher
      uses: korelstar/xmllint-problem-matcher@v1
    - name: Validate articles
      uses: ChristophWurst/xmllint-action@master
      with:
        xml-file: articles/[0-9]*/*.xml
        xml-schema-file: common/schema/DHQauthor-TEI.rng
        xml-schema-type: relaxng
