name: validate schematron

on: [push]

jobs:
  validate-schematron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Enable xmllint matcher
      uses: korelstar/xmllint-problem-matcher@v1
    - name: Validate articles
      uses: ChristophWurst/xmllint-action@master
      with:
        xml-file: articles/[0-9]*/*.xml
        xml-schema-file: common/schema/dhqTEI-ready.sch
        xml-schema-type: schematron
